---
apiVersion: kuma.io/v1alpha1
kind: Mesh
metadata:
  name: default
spec:
  logging:
    defaultBackend: loki
    backends:
      - name: loki
        type: file
        conf:
          path: /dev/stdout
  tracing:
    defaultBackend: zipkin-collector
    backends:
      - name: zipkin-collector
        type: zipkin
        sampling: 100.0
        conf:
          url: http://otel-collector.tracing:9411/api/v2/spans
      - name: jaeger-collector
        type: zipkin
        sampling: 100.0
        conf:
          url: http://jaeger-collector.kuma-tracing:9411/api/v2/spans
---
apiVersion: kuma.io/v1alpha1
kind: TrafficTrace
mesh: default
metadata:
  name: trace-all-traffic
spec:
  selectors:
    - match:
        kuma.io/service: '*'
  conf:
    backend: zipkin-collector
---
apiVersion: kuma.io/v1alpha1
kind: TrafficLog
metadata:
  name: all-traffic
mesh: default
spec:
  # This TrafficLog policy applies all traffic in that Mesh.
  sources:
    - match:
        kuma.io/service: '*'
  destinations:
    - match:
        kuma.io/service: '*'
  # When `backend ` field is omitted, the logs will be forwarded into the `defaultBackend` of that Mesh.

